# Default versions of tools, to update these, set [tools.override]
[tools]
dprint = "latest"
golang = "1.26.0"
golangci-lint = "2.8.0"
goreleaser = "latest"
gotestsum = "1.13.0"
"go:golang.org/x/tools/cmd/goimports" = "latest"
shfmt = "latest"
git-cliff = "latest"

[tasks.build]
description = "Build a binary for the current platform/architecture"
run = "go build -trimpath -o ./bin/ -v ./cmd/..."

[tasks.fmt]
alias = "format"
description = "Format code"
run = ["go mod tidy", "gofmt -s -w .", "goimports -w .", "shfmt -w ."]

[tasks.lint]
description = "Run linters"
run = "golangci-lint run"

[tasks.test]
description = "Run tests"
run = "gotestsum"

## <<Stencil::Block(custom)>>
## <</Stencil::Block>>
