name: release

on:
  # Only run when triggered through the Github UI or API.
  workflow_dispatch:
    inputs:
      version:
        description: "Set a specific version to release"
        required: true
        type: string

permissions:
  contents: write
  packages: write
  issues: write
  # Used by attestations in the release workflow.
  id-token: write
  attestations: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: jdx/mise-action@v3
      - name: Setup syft
        run: mise use -g syft@latest
      - name: Get Go directories
        id: go
        run: |
          echo "cache_dir=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
          echo "mod_cache_dir=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v5
        with:
          path: ${{ steps.go.outputs.cache_dir }}
          key: ${{ github.workflow }}-${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
      - uses: actions/cache@v5
        with:
          path: ${{ steps.go.outputs.mod_cache_dir }}
          key: ${{ github.workflow }}-${{ runner.os }}-go-mod-cache-${{ hashFiles('**/go.sum') }}
      - name: Set up git user and auth
        run: |-
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf "https://github.com/"
      - name: Create release
        env:
          VERSION: ${{ inputs.version }}
          GH_TOKEN: ${{ github.token }}
        run: |-
          ./scripts/release.sh "$VERSION"
          git fetch origin --force --tags
          git checkout "refs/tags/$VERSION"
      - uses: actions/attest-build-provenance@v3
        with:
          subject-checksums: "*"
