name: release

on:
  # Only run when triggered through the Github UI or API.
  workflow_dispatch:
    inputs:
      version:
        description: "Set a specific version to release"
        required: true
        type: string

permissions:
  contents: write
  packages: write
  issues: write
  # Used by attestations in the release workflow.
  id-token: write
  attestations: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup syft
        run: mise use -g syft@latest
      - uses: jdx/mise-action@v3
      - name: Get Go directories
        id: go
        run: |
          echo "cache_dir=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
          echo "mod_cache_dir=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v5
        with:
          path: ${{ steps.go.outputs.cache_dir }}
          key: ${{ github.workflow }}-${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
      - uses: actions/cache@v5
        with:
          path: ${{ steps.go.outputs.mod_cache_dir }}
          key: ${{ github.workflow }}-${{ runner.os }}-go-mod-cache-${{ hashFiles('**/go.sum') }}
      - name: Create release
        env:
          VERSION: ${{ inputs.version }}
        run: |-
          ./scripts/release.sh "$VERSION"
          git fetch origin --tags
          git checkout "origin/refs/tags/$VERSION"
      - uses: actions/attest-build-provenance@v3
        with:
          subject-checksums: action-go-shim*
